name: GangaDirac Testing

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install -e .
    - name: Lint with flake8
      run: |
        python3 -m pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        # disable for now
        flake8 . --count --exit-zero --exclude doc --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  unit:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        container: ["centos:7"]

    container: ${{ matrix.container }}
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3
      run: yum install -y python3
#      uses: actions/setup-python@v1
#      with:
#        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install -e .
        python3 -m pip install coverage pytest pytest-cov pytest-pylint pytest-mock
    - name: Test with pytest
      env: # Or as an environment variable
        ROBOT_CERT: ${{ secrets.GangaRobot_UserCert }}
        ROBOT_KEY: ${{ secrets.GangaRobot_UserKey }}
      run: echo Hello
        mkdir -p ~/.globus
        echo $ROBOT_CERT > ~/.globus/usercert.pem
        echo $ROBOT_KEY > ~/.globus/userkey.pem
        python3 -m pytest --cov-report term --cov ganga/GangaDirac ganga/GangaDirac/test/Unit
